"""criar tabelas iniciais

Revision ID: 2b416350f951
Revises: 
Create Date: 2026-08-05 13:05:45.127364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b416350f951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('convenio', sa.Enum('UNIMED', 'BRADESCO_SAUDE', 'SULAMERICA', name='convenioenum'), nullable=False),
    sa.Column('numero_carteirinha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_hora_chegada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'CONCLUIDO', 'ARQUIVADO', name='statusatendimentoenum'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_table('altas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_altas_id'), 'altas', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('descricao_medico', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_exame', sa.Enum('HEMOGRAMA', 'RAIO_X', 'ECG', name='tipoexameenum'), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADO', 'CONCLUIDO', name='statusexameenum'), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_id'), 'exames', ['id'], unique=False)
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('nome_medicacao', sa.Enum('DIPIRONA', 'PARACETAMOL', 'BUSCOPAN', 'ONDANSETRONA', name='tipomedicamentoenum'), nullable=False),
    sa.Column('dosagem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_table('triagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('sintomas', sa.String(), nullable=False),
    sa.Column('pressao_arterial', sa.String(), nullable=False),
    sa.Column('cor_classificacao', sa.Enum('VERMELHO', 'LARANJA', 'AMARELO', name='corclassificacaoenum'), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triagens_id'), 'triagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triagens_id'), table_name='triagens')
    op.drop_table('triagens')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_exames_id'), table_name='exames')
    op.drop_table('exames')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_altas_id'), table_name='altas')
    op.drop_table('altas')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
